### Get login user data
GET http://localhost/api/user
Content-Type: application/json
Accept: application/json
Authorization: Bearer 76|YFX2PHLHb7Id9SeQpwXfL7YpMvlGBE6jljGrk7m7


### log in API 
POST http://localhost/api/authenticate
Content-Type: application/json
Accept: application/json

{
    "user_id" : "2",
    "one_time_token":"louI3CG7s54hHEadvQ24tk2stjTWclF2o9HE8HKC"
}

### get CSRF 
GET http://localhost:8081/sanctum/csrf-cookie
Content-Type: application/json
Accept: application/json
X-Requested-With: XMLHttpRequest
