version: '3'
services:
        nginx:
                image: nginx:1.15
                ports:
                  - "0.0.0.0:8081:80"
                volumes:
                        - mutagen-volume:/usr/share/nginx/html
                        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
                        - ./nginx/mime.conf:/etc/nginx/conf.d/mime.conf
        php-fpm:
                build: ./php-fpm
                volumes:
                        - mutagen-volume:/var/www/html
        mysql:
                image: mysql:5.7
                environment:
                        MYSQL_DATABASE: ebiten 
                        MYSQL_ROOT_PASSWORD: password
                        MYSQL_USER: user
                        MYSQL_PASSWORD: password
                        TZ: Asia/Tokyo
                ports:
                        - 3306:3306
                volumes:
                        - ./mysql/data:/var/lib/mysql
volumes:
  mutagen-volume:

x-mutagen:
  sync:
    mutagen-volume:
      mode: "two-way-resolved"
      alpha: "./src" 
      beta: "volume://mutagen-volume"
